### PR TITLE
fix: correct branch name and resume session

### LINKED ISSUE #1114: Git clone fails when resuming a session
Logs:

```
2026/04/28 07:28:24 Checking if clone path: /home/renku/work/renku-envs exists
2026/04/28 07:28:24 Processing https://gitlab.com/leafty/renku-envs.git
2026/04/28 07:28:24 Checking if the repo already exists.
2026/04/28 07:28:24 Setting up git proxy to http://localhost:65480
2026/04/28 07:28:24 Initializing repo
2026/04/28 07:28:24 Setting email flora.thiebaut@sdsc.ethz.ch in git config
2026/04/28 07:28:24 Setting name Flora Thiebaut in git config
2026/04/28 07:28:24 Cloning repository /home/renku/work/renku-envs from https://gitlab.com/leafty/renku-envs.git
2026/04/28 07:28:24 Cloning failed for https://gitlab.com/leafty/renku-envs.git: git failed: exit status 3, error: remote origin already exists.
```

Some options:
1. Overwrite the existing remote (e.g. `git remote remove` then `git remote add` or do it on the gitconfig)
2. Just skip that step

cc @sgaist

### LINKED ISSUE #1115: Git clone sets up detached branches
The local git repository is not set to track the remote branch.

Logs:
```
2026/04/28 07:34:19 Checking if clone path: /home/renku/work/renku-envs exists
2026/04/28 07:34:19 Creating clone path
2026/04/28 07:34:19 Processing https://gitlab.com/leafty/renku-envs.git
2026/04/28 07:34:19 Checking if the repo already exists.
2026/04/28 07:34:19 Initializing repo
2026/04/28 07:34:19 Setting email flora.thiebaut@sdsc.ethz.ch in git config
2026/04/28 07:34:19 Setting name Flora Thiebaut in git config
2026/04/28 07:34:19 Cloning repository /home/renku/work/renku-envs from https://gitlab.com/leafty/renku-envs.git
2026/04/28 07:34:20 Default branch is refs/remotes/origin/main
2026/04/28 07:34:20 Checking out branch refs/remotes/origin/main
2026/04/28 07:34:20 Dealing with submodules
2026/04/28 07:34:20 Setting up git proxy to http://localhost:65480
```

Terminal:
```
cd renku-envs/
 ~ ▶ work ❯ renku-envs ▶ ⚓ e4ae94a ▶ $ ▶ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

 ~ ▶ work ❯ renku-envs ▶ ⚓ e4ae94a ▶ $ ▶ git status
HEAD detached at origin/main
nothing to commit, working tree clean
```

cc @sgaist

### PR DESCRIPTION
**Pull request by leafty**
Fixes:
* Closes #1115: parse the branch name, the git repository tracks the default remote branch
* Closes #1114: correctly skip git cloning when resuming, re-set the git-proxy settings as expected
* Fixes cloning an empty repository

/deploy #notest extra-values=notebooks.gitClone.image.name=renku/cloner,notebooks.gitClone.image.tag=0.27.2-0.dev.git.368.h8171201

### CODE REVIEW

File: internal/cloner/repository.go [hunk 1]
```diff
@@ -67,18 +67,21 @@ func (r *Repository) Exists() bool {
...
 		return "", err
 	}
 	rx := regexp.MustCompile(fmt.Sprintf(`refs/remotes/%v/(?P<branch>.*)`, remoteName))
-	branch := rx.FindString(ref)
-
-	if branch == "" {
-		return "", fmt.Errorf("branch does not exist")
+	match := rx.FindStringSubmatch(ref)
+	if match == nil {
+		// TODO: is this correct? check with an empty git repository
```
Comment (leafty) [inline internal/cloner/repository.go]:
```suggestion
```

**Review by sgaist — APPROVED** [review]
