### PR TITLE
fix: handle reserved annotations for PVCs

### LINKED ISSUE #1102: very high log generation for a hibernated session
We have seen this when amalthea is running on a AWS managed k8s instance in a remote cluster.

To reproduce:
1. Start a session
2. Wait for it to hibernate for inactivity
3. See the logs - there will be a lot generated for the hibernation date checks

```
2026-04-10T08:29:25Z    INFO    hibernationDate    {"controller": "amaltheasession", "controllerGroup": "amalthea.dev", "controllerKind": "AmaltheaSession
", "AmaltheaSession": {"name":"tasko-olevsk-9482264f7d80","namespace":"renku-user-sessions"}, "namespace": "renku-user-sessions", "name": "tasko-olevsk-94
82264f7d80", "reconcileID": "671e40fe-f9c5-4f0d-89b1-f901ff03adbc", "DecisionLog": "=> NONE"}
2026-04-10T08:29:25Z    INFO    hibernationDate    {"controller": "amaltheasession", "controllerGroup": "amalthea.dev", "controllerKind": "AmaltheaSession
", "AmaltheaSession": {"name":"tasko-olevsk-9482264f7d80","namespace":"renku-user-sessions"}, "namespace": "renku-user-sessions", "name": "tasko-olevsk-94
82264f7d80", "reconcileID": "24d613ae-9f1e-440f-8dd6-9118c25f9133", "DecisionLog": "=> NONE"}
2026-04-10T08:29:25Z    INFO    hibernationDate    {"controller": "amaltheasession", "controllerGroup": "amalthea.dev", "controllerKind": "AmaltheaSession
", "AmaltheaSession": {"name":"tasko-olevsk-9482264f7d80","namespace":"renku-user-sessions"}, "namespace": "renku-user-sessions", "name": "tasko-olevsk-94
82264f7d80", "reconcileID": "820833c4-d7b3-4966-8fbf-f1701a3282ce", "DecisionLog": "=> NONE"}
```

### PR DESCRIPTION
**Pull request by leafty**
Closes #1102.

Details:
1. fix the `reconcileAfter` logic
2. handle reserved annotations for PVCs

TODO: refactor to make re-usable util functions for reserved labels, annotations and taints.

/deploy

### CODE REVIEW

File: internal/controller/children.go [hunk 1]
```diff
@@ -186,8 +186,22 @@ func (c ChildResource[T]) Reconcile(ctx context.Context, clnt client.Client, cr
...
+					domain, _, _ := strings.Cut(key, "/")
+					if domain == "kubernetes.io" || domain == "k8s.io" || strings.HasSuffix(domain, ".kubernetes.io") ||
+						strings.HasSuffix(domain, ".k8s.io") {
+						preservedAnnotations[key] = current.Annotations[key]
+					}
+				}
 				current.Annotations = desired.Annotations
+				for key := range preservedAnnotations {
+					current.Annotations[key] = preservedAnnotations[key]
+				}
```
Comment (leafty) [inline internal/controller/children.go:207]: TODO: refactor this into re-usable util methods and use for all k8s resources.

**Review by olevski — DISMISSED** [review]

**Review by olevski — APPROVED** [review]
